# Generated by Django 6.0.3 on 2026-04-16 02:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("authorID", models.AutoField(primary_key=True, serialize=False)),
                ("first", models.CharField(max_length=255)),
                ("last", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, max_length=4111)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "Authors",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("first", models.CharField(max_length=255)),
                ("last", models.CharField(max_length=255)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("mailing_address", models.CharField(blank=True, max_length=255)),
                ("zipcode", models.CharField(blank=True, max_length=255)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "Users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("bookID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("series_name", models.CharField(blank=True, max_length=255)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("pub_date", models.DateField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("in_circulation_from", models.DateField(blank=True, null=True)),
                ("in_circulation_until", models.DateField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        db_column="authorID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.author",
                    ),
                ),
            ],
            options={
                "db_table": "Books",
            },
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("out_time", models.DateTimeField()),
                ("in_time", models.DateTimeField(blank=True, null=True)),
                ("due_time", models.DateTimeField()),
                (
                    "fine",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "book",
                    models.ForeignKey(
                        db_column="bookID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Checkouts",
                "unique_together": {("user", "book", "out_time")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_column="authorID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.author",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "FavoriteAuthors",
                "unique_together": {("user", "author")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_column="authorID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.author",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        db_column="bookID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "FavoriteBooks",
                "unique_together": {("user", "book", "author")},
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("promID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discount_percent",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "book",
                    models.ForeignKey(
                        db_column="bookID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                    ),
                ),
            ],
            options={
                "db_table": "Promotions",
                "unique_together": {("promID", "book")},
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        db_column="bookID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Reservations",
                "unique_together": {("user", "book")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=255)),
                (
                    "score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        db_column="bookID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Reviews",
                "unique_together": {("user", "book")},
            },
        ),
    ]
