# Generated by Django 6.0.2 on 2026-04-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                db_column="authorID",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.author",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="authorID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="bookID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="promID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="userID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "book", "author")},
        ),
    ]
